// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTy_oAiV8qPomGH0qh1-Nor7n3YOw1sBo',
    appId: '1:971178204261:web:bb821145482e695377fa8c',
    messagingSenderId: '971178204261',
    projectId: 'my-finance-c88f7',
    authDomain: 'my-finance-c88f7.firebaseapp.com',
    storageBucket: 'my-finance-c88f7.firebasestorage.app',
    measurementId: 'G-Y7QWK4ZSYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUccPlzRuGw3ad9NEpE0j9QLKp9BV6UGw',
    appId: '1:971178204261:android:20604fef2b17c71d77fa8c',
    messagingSenderId: '971178204261',
    projectId: 'my-finance-c88f7',
    storageBucket: 'my-finance-c88f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4U27xPW6uBHuGTjqK7THOezZBYO6ya0g',
    appId: '1:971178204261:ios:a35b677818f512d477fa8c',
    messagingSenderId: '971178204261',
    projectId: 'my-finance-c88f7',
    storageBucket: 'my-finance-c88f7.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );
}
